name: census-viz
channels:
  - pyviz
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - attrs=18.2.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.0.2
  - bokeh=1.0.3
  - bzip2=1.0.6
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - cartopy=0.17.0
  - certifi=2018.11.29
  - cffi=1.11.5
  - cftime=1.0.3.4
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.0.4
  - cligj=0.5.0
  - cloudpickle=0.6.1
  - colorcet=1.0.0
  - cryptography=2.4.2
  - curl=7.63.0
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=1.0.0
  - dask-core=1.0.0
  - datashape=0.5.4
  - dbus=1.13.2
  - decorator=4.3.0
  - descartes=1.1.0
  - distributed=1.25.1
  - entrypoints=0.2.3
  - expat=2.2.6
  - fiona=1.8.4
  - fontconfig=2.13.0
  - freetype=2.9.1
  - freexl=1.0.5
  - futures-compat=1.0
  - gdal=2.3.3
  - geopandas=0.4.0
  - geos=3.7.1
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.56.2
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.0
  - icu=58.2
  - idna=2.8
  - imageio=2.4.1
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.2
  - jinja2=2.10
  - jpeg=9b
  - json-c=0.13.1
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kealib=1.4.7
  - kiwisolver=1.0.1
  - krb5=1.16.1
  - libboost=1.67.0
  - libcurl=7.63.0
  - libdap4=3.19.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgdal=2.3.3
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.35
  - libpq=11.1
  - libsodium=1.0.16
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvmlite=0.27.0
  - locket=0.2.0
  - lxml=4.2.5
  - markupsafe=1.1.0
  - matplotlib=3.0.2
  - mistune=0.8.4
  - mkl=2019.1
  - mkl_fft=1.0.6
  - mkl_random=1.0.2
  - msgpack-python=0.5.6
  - multipledispatch=0.6.0
  - munch=2.3.2
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf4=1.4.2
  - networkx=2.2
  - notebook=5.7.4
  - numba=0.42.0
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1a
  - owslib=0.17.0
  - packaging=18.0
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - param=1.8.1
  - parso=0.3.1
  - partd=0.3.9
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pip=18.1
  - pixman=0.34.0
  - poppler=0.65.0
  - poppler-data=0.4.9
  - proj4=5.2.0
  - prometheus_client=0.5.0
  - prompt_toolkit=2.0.7
  - psutil=5.4.8
  - psycopg2=2.7.6.1
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pyct=0.4.5
  - pyct-core=0.4.5
  - pyepsg=0.4.0
  - pygments=2.3.1
  - pykdtree=1.3.1
  - pyopenssl=18.0.0
  - pyparsing=2.3.0
  - pyproj=1.9.5.1
  - pyqt=5.9.2
  - pysal=1.14.4.post1
  - pyshp=2.0.1
  - pysocks=1.6.8
  - python=3.7.2
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pywavelets=1.0.1
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.9.7
  - qtconsole=4.4.3
  - readline=7.0
  - requests=2.21.0
  - rtree=0.8.3
  - scikit-image=0.14.1
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=40.6.3
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.12.0
  - sortedcontainers=2.1.0
  - sqlalchemy=1.2.15
  - sqlite=3.26.0
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1.1
  - traitlets=4.3.2
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.32.3
  - widgetsnbextension=3.4.2
  - xarray=0.11.0
  - xerces-c=3.2.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zlib=1.2.11
  - datashader=0.6.8
  - geoviews=1.6.0
  - geoviews-core=1.6.0
  - holoviews=1.11.0
  - pyviz_comms=0.7.0
  - pip:
    - census==0.8.10
    - future==0.17.1
    - jellyfish==0.5.6
    - msgpack==0.5.6
    - us==1.0.0
